version: '3'
services:
#  webdirectory-api:
#    image: canals/php:8.2
#    build: ./api
#    ports:
#      - "5000:5000"
#    environment:
#      - DB_HOST=db
#      - DB_PORT=5432
#      - DB_USER=youruser
#      - DB_PASSWORD=yourpassword
#      - DB_NAME=webdirectory
#    depends_on:
#      - db
#
#  webdirectory-admin:
#    build: ./admin
#    ports:
#      - "3000:3000"
#    depends_on:
#      - webdirectory-api

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "42194:8080"

  db:
    image: mariadb:latest
    container_name: giftbox_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      #MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "42195:3306"

volumes:
  db_data: