services:
  # --- API Service ---
  api:
    image: canals/php:8.2
    container_name: webdirectory_api
    volumes:
      - ./WebDir.core/public:/var/www/html
      - ./WebDir.core/src:/var/www/src
    ports:
      - "42190:8080"

  # --- PHP Service ---
  php:
    image: canals/php:8.2
    container_name: webdirectory_php
    volumes:
      - ./WebDir.core/public:/var/www/html
      - ./WebDir.core/src:/var/www/src
    ports:
      - "42191:8081"

  # --- WebDir.app (Flutter) ---
  webdir_app:
    image: cirrusci/flutter
    container_name: webdirectory_flutter
    volumes:
      - ./WebDir.app:/app
    command: flutter run --web --web-port 8082
    ports:
      - "42192:8082"

  # --- WebDir.web (JavaScript) ---
  webdir_web:
    image: node:16
    container_name: webdirectory_web
    volumes:
      - ./WebDir.web:/app
    working_dir: /app
    command: npm start
    ports:
      - "42193:3000"

volumes:
  db_data:
