version: '3.8'

networks:
  web.net:
    driver: bridge

services:
  # --- API Service ---
  api:
    image: canals/php:8.2
    container_name: webdirectory_api
    working_dir: /var/www/html
    volumes:
      - ./WebDir.api/public:/var/www/html
      - ./WebDir.api/src:/var/www/html/src
    command: php -S 0.0.0.0:8080 -t /var/www/html/
    ports:
      - "42190:8080"
    networks:
      - web.net

  # --- PHP Service ---
  php:
    image: canals/php:8.2
    working_dir: /var/www/html
    container_name: webdirectory_php
    volumes:
      - ./WebDir.core/public:/var/www/html
      - ./WebDir.core/src:/var/www/html/src
    ports:
      - "42191:8081"
    networks:
      - web.net
    depends_on:
      - db

  # --- WebDir.app (Flutter) ---
  webdir_app:
    image: mobiledevops/flutter-sdk-image:3.16.3
    container_name: webdirectory_app
    platform: linux/amd64
    volumes:
      - ./WebDir.app:/app
    ports:
      - "42192:8082"
    networks:
      - web.net

  # --- WebDir.web (JavaScript) ---
  webdir_web:
    image: node:16
    container_name: webdirectory_web
    volumes:
      - ./WebDir.web:/var/www/html/web
    working_dir: /var/www/html/web
    ports:
      - "42193:3000"
    networks:
      - web.net
    command: npm run start

  # --- Database Service ---
  db:
    image: mariadb:latest
    container_name: webdirectory_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "42194:3306"  # Corrected port mapping
    networks:
      - web.net

  # --- Adminer Service ---
  adminer:
    image: adminer:latest
    container_name: webdirectory_adminer
    ports:
      - "42195:8080"  # Corrected port mapping
    networks:
      - web.net

volumes:
  db_data:
