version: '3.8'

networks:
  web.net:
    driver: bridge

services:

  web_and_api:
    image: canals/php:8.2
    container_name: webdirectory_combined
    working_dir: /var/www/html
    volumes:
      - ./WebDir.web/public:/var/www/html
      - ./WebDir.api/src:/var/www/html/api/src
      - ./WebDir.api/public:/var/www/html/api
      - ./shared/img:/var/www/html/src/user-img
    command: php -S 0.0.0.0:8080 -t /var/www/html/
    ports:
      - "42190:8080"
    networks:
      - web.net
    restart: unless-stopped

  # --- PHP Service ---
  php:
    image: canals/php:8.2
    working_dir: /var/www/html
    container_name: webdirectory_php
    volumes:
      - ./WebDir.core/public:/var/www/html
      - ./WebDir.core/src:/var/www/html/src
      - ./shared/img:/var/www/html/src/user-img
    ports:
      - "42191:80"
    networks:
      - web.net
    restart: unless-stopped

  # --- Database Service ---
  db:
    image: mariadb:latest
    container_name: webdirectory_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "42194:3306" 
    networks:
      - web.net

  # --- Adminer Service ---
  adminer:
    image: adminer:latest
    container_name: webdirectory_adminer
    ports:
      - "42195:8080"
    networks:
      - web.net
    command : php -S 0.0.0.0:8080 -t /var/www/html
